# Generated by Django 2.2.4 on 2019-08-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=50)),
                ('level', models.IntegerField(blank=True)),
                ('wait_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
