import React,{Component} from 'react';
import Header from './header-footer/header';
import Footer from './header-footer/footer';
class Rules extends Component{
    constructor(props){
        super(props);
        this.state={

        };
    };

    render(){
        return(
            <div>
                <header>
                    <Header />
                </header>
                <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sagittis id consectetur purus ut. Ornare arcu odio ut sem nulla pharetra diam sit. Aliquam nulla facilisi cras fermentum odio eu feugiat. Nulla malesuada pellentesque elit eget gravida cum sociis natoque. Quis varius quam quisque id diam vel quam elementum. Sapien et ligula ullamcorper malesuada proin. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Egestas quis ipsum suspendisse ultrices. Aliquet bibendum enim facilisis gravida neque. Non arcu risus quis varius quam quisque id diam vel. Aliquam vestibulum morbi blandit cursus risus at ultrices. Sit amet porttitor eget dolor morbi non arcu. Volutpat blandit aliquam etiam erat velit. Quisque sagittis purus sit amet volutpat consequat mauris nunc congue.

Euismod in pellentesque massa placerat duis. Faucibus et molestie ac feugiat sed lectus vestibulum. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Faucibus purus in massa tempor nec feugiat nisl pretium fusce. Purus semper eget duis at tellus at urna. Lacus sed turpis tincidunt id. Quam viverra orci sagittis eu volutpat odio. Iaculis at erat pellentesque adipiscing. Tellus molestie nunc non blandit massa enim nec. At in tellus integer feugiat scelerisque varius morbi. Consequat interdum varius sit amet mattis vulputate enim nulla aliquet. Porttitor rhoncus dolor purus non enim praesent elementum. Urna porttitor rhoncus dolor purus non. Gravida in fermentum et sollicitudin. Sit amet nisl suscipit adipiscing bibendum. Eget velit aliquet sagittis id consectetur purus ut faucibus pulvinar.

Cras adipiscing enim eu turpis egestas pretium. Ultricies integer quis auctor elit sed vulputate mi. Vel quam elementum pulvinar etiam non quam. Morbi blandit cursus risus at ultrices. Tellus pellentesque eu tincidunt tortor aliquam nulla facilisi. In metus vulputate eu scelerisque felis imperdiet proin fermentum leo. Augue interdum velit euismod in pellentesque massa placerat duis ultricies. Quam quisque id diam vel quam. Ultrices vitae auctor eu augue ut. Neque sodales ut etiam sit amet. Nulla pellentesque dignissim enim sit amet venenatis urna cursus eget. Scelerisque viverra mauris in aliquam sem.

A diam maecenas sed enim ut sem viverra aliquet eget. Sed faucibus turpis in eu mi bibendum. Fermentum dui faucibus in ornare quam viverra orci sagittis. Nec dui nunc mattis enim ut tellus. Duis tristique sollicitudin nibh sit amet commodo. Maecenas pharetra convallis posuere morbi leo urna. Felis eget nunc lobortis mattis aliquam faucibus purus in. Fermentum et sollicitudin ac orci. Eget nunc lobortis mattis aliquam faucibus purus in massa. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Et tortor at risus viverra adipiscing at in tellus. Morbi tincidunt augue interdum velit. Maecenas accumsan lacus vel facilisis volutpat est velit egestas dui. Proin fermentum leo vel orci porta non pulvinar. Nibh praesent tristique magna sit amet purus gravida quis. Quis auctor elit sed vulputate mi sit amet mauris commodo. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper.

In egestas erat imperdiet sed euismod nisi porta. Orci dapibus ultrices in iaculis nunc sed augue. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget. Pellentesque dignissim enim sit amet venenatis urna cursus. A iaculis at erat pellentesque adipiscing. Et leo duis ut diam quam nulla. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien. In tellus integer feugiat scelerisque varius morbi enim nunc faucibus. Et leo duis ut diam quam nulla porttitor massa id. Libero nunc consequat interdum varius sit amet mattis. Bibendum neque egestas congue quisque egestas diam in arcu. Scelerisque purus semper eget duis at tellus at urna. Vestibulum morbi blandit cursus risus at. A iaculis at erat pellentesque adipiscing commodo elit at. Vel pharetra vel turpis nunc eget lorem dolor sed. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Lacus vestibulum sed arcu non. Feugiat pretium nibh ipsum consequat nisl vel pretium.

Volutpat ac tincidunt vitae semper quis. Nisl purus in mollis nunc sed. A cras semper auctor neque vitae tempus. Tristique nulla aliquet enim tortor at auctor urna nunc. Diam maecenas sed enim ut. Elit scelerisque mauris pellentesque pulvinar pellentesque. Fringilla ut morbi tincidunt augue interdum velit euismod in. Condimentum lacinia quis vel eros donec ac odio. In est ante in nibh mauris cursus mattis. Consequat nisl vel pretium lectus quam id leo in vitae. Dictum varius duis at consectetur lorem donec. Nec feugiat in fermentum posuere urna nec tincidunt praesent semper. Volutpat ac tincidunt vitae semper quis. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit. Et leo duis ut diam quam nulla porttitor massa. Volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque in. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed.

Urna nec tincidunt praesent semper feugiat nibh sed pulvinar. Vehicula ipsum a arcu cursus vitae congue mauris rhoncus aenean. Sed faucibus turpis in eu mi bibendum neque egestas. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Sed ullamcorper morbi tincidunt ornare. Enim facilisis gravida neque convallis a cras semper auctor neque. Ut eu sem integer vitae justo eget magna fermentum iaculis. Amet massa vitae tortor condimentum. Gravida cum sociis natoque penatibus et magnis dis parturient montes. Id interdum velit laoreet id donec ultrices tincidunt. A diam maecenas sed enim ut sem viverra. Maecenas sed enim ut sem viverra aliquet eget. Eu feugiat pretium nibh ipsum consequat nisl vel. Turpis egestas sed tempus urna et pharetra pharetra. Urna molestie at elementum eu. Ultricies mi eget mauris pharetra et ultrices neque ornare aenean. Aliquet nibh praesent tristique magna sit. Sit amet porttitor eget dolor morbi non arcu risus quis.

Massa massa ultricies mi quis hendrerit dolor magna. Amet massa vitae tortor condimentum lacinia. Morbi enim nunc faucibus a pellentesque sit. Lorem dolor sed viverra ipsum. Morbi tincidunt augue interdum velit euismod. Risus at ultrices mi tempus imperdiet nulla. Enim diam vulputate ut pharetra sit amet aliquam. Purus non enim praesent elementum facilisis leo. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Porttitor massa id neque aliquam vestibulum morbi. Dignissim diam quis enim lobortis scelerisque fermentum dui. Tincidunt lobortis feugiat vivamus at augue. Mauris in aliquam sem fringilla ut morbi. Massa sapien faucibus et molestie ac feugiat. Libero enim sed faucibus turpis in eu mi bibendum neque. Odio morbi quis commodo odio aenean sed adipiscing diam. Porta nibh venenatis cras sed felis. Sed id semper risus in hendrerit gravida rutrum quisque non. At erat pellentesque adipiscing commodo elit at imperdiet dui.

Tincidunt tortor aliquam nulla facilisi cras fermentum. Tellus rutrum tellus pellentesque eu. Dolor sed viverra ipsum nunc. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Quam adipiscing vitae proin sagittis nisl. Sem et tortor consequat id porta nibh venenatis cras. Lobortis feugiat vivamus at augue eget arcu dictum. Aenean et tortor at risus viverra adipiscing at in tellus. At in tellus integer feugiat scelerisque varius morbi enim. Diam sit amet nisl suscipit. Facilisis mauris sit amet massa vitae tortor condimentum lacinia quis. Porta lorem mollis aliquam ut. Sagittis nisl rhoncus mattis rhoncus urna. Porta lorem mollis aliquam ut porttitor leo a. Tortor vitae purus faucibus ornare suspendisse sed nisi. Nibh ipsum consequat nisl vel pretium lectus quam. Orci nulla pellentesque dignissim enim sit. Nec sagittis aliquam malesuada bibendum arcu. Nulla aliquet porttitor lacus luctus accumsan tortor posuere. Id porta nibh venenatis cras sed.

Turpis in eu mi bibendum. Enim lobortis scelerisque fermentum dui faucibus. Facilisis volutpat est velit egestas dui. Eleifend donec pretium vulputate sapien nec sagittis aliquam. Quam adipiscing vitae proin sagittis nisl rhoncus. Ut faucibus pulvinar elementum integer enim neque. Ut tellus elementum sagittis vitae. Pellentesque habitant morbi tristique senectus et netus et malesuada. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc consequat. Et netus et malesuada fames ac turpis. Risus at ultrices mi tempus imperdiet. Nunc sed id semper risus in hendrerit gravida rutrum quisque. A arcu cursus vitae congue. Sociis natoque penatibus et magnis dis parturient montes nascetur. Neque ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Quis eleifend quam adipiscing vitae proin. Ipsum a arcu cursus vitae congue mauris rhoncus aenean vel. Est ullamcorper eget nulla facilisi. Condimentum lacinia quis vel eros donec ac. Consectetur libero id faucibus nisl.
                </p>
                <footer>
                    <Footer />
                </footer>    
            </div> 
        );
    }
}

export default Rules;