# Generated by Django 2.2.4 on 2019-09-27 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_player_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='unlock_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_solved',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
