# Generated by Django 2.2.4 on 2019-10-05 04:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190927_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_solved',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='player',
            name='unlock_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
