# Generated by Django 2.2.4 on 2019-10-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191005_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.ImageField(default='1.png', upload_to='img/'),
        ),
        migrations.AddField(
            model_name='player',
            name='avatar_no',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
